export const
    SET_TOKEN = "SET_TOKEN",
    SET_IS_404 = "SET_IS_404",
    SET_IS_LOADING_PAGE = "SET_IS_LOADING_PAGE",
    SET_IS_OPEN_SIDE_BAR = "SET_IS_OPEN_SIDE_BAR",
    SET_NOTIFY = "SET_NOTIFY",
    SET_USER_INFO = "SET_USER_INFO",
    SET_USER_BLOGS = "SET_USER_BLOGS",
    SET_INPUT_SEARCH_HOME = "SET_INPUT_SEARCH_HOME"
